/**
 * ============================================================
 * EXERCISE 01 — REST Service with HttpClient
 * ============================================================
 *
 * REST = Representational State Transfer
 * It's a convention for how URLs + HTTP verbs map to CRUD actions:
 *
 *   GET    /products          → list all
 *   GET    /products/42       → get one by id
 *   POST   /products          → create new (body = new item)
 *   PUT    /products/42       → replace entire item
 *   PATCH  /products/42       → partial update (just the changed fields)
 *   DELETE /products/42       → remove
 *
 * HTTP is the transport; REST is the convention on HOW you use it.
 *
 * HOW IT'S DONE IN YOUR PROJECT (UsersService):
 *   - inject(HttpClient)           → low-level HTTP
 *   - injectBaseUrl()              → builds the full URL from env config
 *   - HttpContext                   → passes per-request flags to interceptors
 *   - getUsers(page, size)         → GET /users?page=1&size=5
 *   - addUser(user)                → POST /users
 *   - updateUser(user)             → PUT /users/:id
 *   - deleteUser(id)               → DELETE /users/:id
 *
 * ★ YOUR TASK ★
 * Implement a ProductsService following the same pattern.
 * All the types are provided below.
 * Replace every /* TODO */

import { HttpClient, HttpContextToken, HttpParams } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';

// ── Types ──────────────────────────────────────────────────────────────────
export interface Product {
  id: string;
  name: string;
  price: number;
  category: 'electronics' | 'clothing' | 'food';
  inStock: boolean;
}

export interface PaginatedProducts {
  data: Product[];
  meta: {
    totalItems: number;
    page: number;
    size: number;
  };
}

// Utility types exercises — use these in the methods below
export type CreateProductPayload = Omit<Product, 'id'>;
export type UpdateProductPayload = Partial<Product>;

// HttpContextToken — same pattern as BYPASS_LOADING_SPINNER in your project
export const SKIP_PRODUCT_CACHE = new HttpContextToken<boolean>(() => false);

// ── Service ───────────────────────────────────────────────────────────────
@Injectable({
  providedIn: 'root',
})
export class ProductsService {
  // TODO: inject HttpClient (look at how UsersService does it)
  private readonly http = inject(HttpClient);

  // Base URL — hardcoded for the exercise (in your real project this uses injectBaseUrl)
  private readonly baseUrl = 'https://api.example.com/products';

  /**
   * GET /products?page=1&size=10
   * Returns a paginated list of products.
   */
  getProducts(page: number = 1, size: number = 10) {
    return this.http.get<PaginatedProducts>(this.baseUrl, {
      params: new HttpParams({
        fromObject: {
          page,
          size,
        },
      }),
    });
  }

  /**
   * GET /products/:id
   * Returns a single product.
   */
  getProduct(id: string) {
    return this.http.get<Product>(`${this.baseUrl}/${id}`);
  }

  /**
   * POST /products
   * Creates a new product (id is generated by the server).
   */
  addProduct(product: CreateProductPayload) {
    return this.http.post<Product>(this.baseUrl, product);
  }

  /**
   * PUT /products/:id
   * Replaces the full product.
   * Note: PUT replaces the ENTIRE resource. All fields required.
   */
  updateProduct(product: Product) {
    return this.http.put<Product>(`${this.baseUrl}/${product.id}`, product);
  }

  /**
   * PATCH /products/:id
   * Partial update — only sends the changed fields.
   * Use UpdateProductPayload (Partial<Product>) as the body type.
   */
  patchProduct(id: string, changes: UpdateProductPayload) {
    return this.http.patch<Product>(`${this.baseUrl}/${id}`, changes);
  }

  /**
   * DELETE /products/:id
   * Removes a product. Returns void (no response body).
   */
  deleteProduct(id: string) {
    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }

  /**
   * GET /products?category=electronics
   * Filter products by category — pass category as a query param.
   */
  getProductsByCategory(category: Product['category']) {
    return this.http.get<Product[]>(`${this.baseUrl}?category=${category}`);
  }
}

// ── ✅ SOLUTION (unfold only after trying) ────────────────────────────────
/*
export type CreateProductPayload = Omit<Product, 'id'>;
export type UpdateProductPayload = Partial<Product>;

private readonly http = inject(HttpClient);

getProducts(page = 1, size = 10) {
  return this.http.get<PaginatedProducts>(`${this.baseUrl}?page=${page}&size=${size}`);
}

getProduct(id: string) {
  return this.http.get<Product>(`${this.baseUrl}/${id}`);
}

addProduct(product: CreateProductPayload) {
  return this.http.post<Product>(this.baseUrl, product);
}

updateProduct(product: Product) {
  return this.http.put<Product>(`${this.baseUrl}/${product.id}`, product);
}

patchProduct(id: string, changes: UpdateProductPayload) {
  return this.http.patch<Product>(`${this.baseUrl}/${id}`, changes);
}

deleteProduct(id: string) {
  return this.http.delete<void>(`${this.baseUrl}/${id}`);
}

getProductsByCategory(category: Product['category']) {
  return this.http.get<Product[]>(`${this.baseUrl}?category=${category}`);
}
*/
